# Generated by Django 3.1.3 on 2021-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
